apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-api
  namespace: monitoring
  labels:
    app.kubernetes.io/name: task-api
    app.kubernetes.io/component: api
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argo-task-api
  selector:
    matchLabels:
      app.kubernetes.io/name: task-api
      app.kubernetes.io/instance: argo-task-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
