apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service-runtime-secrets
  namespace: notification-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: notification-service-runtime-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: NOTIFY_WEBHOOK_URL
      remoteRef:
        key: /aws-eks-terraform-lab/dev/observability/slack
        property: TASK_COMPLETION_WEBHOOK_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
