apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-api-runtime-secrets
  namespace: argo-task-api
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: task-api-runtime-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /aws-eks-terraform-lab/dev/task-api/database
        property: DB_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /aws-eks-terraform-lab/dev/redis/auth
        property: REDIS_PASSWORD
