apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-task-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/leehrm/task-api-platform.git
    targetRevision: main
    path: helm/task-api
    helm:
      values: |
        postgresdb:
          enabled: false

        image:
          repository: 519330023984.dkr.ecr.ap-northeast-1.amazonaws.com/task-api
          tag: "d2ba868"
          pullPolicy: Always

        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 8
          targetCPUUtilizationPercentage: 60
          behavior:
            scaleDown:
              stabilizationWindowSeconds: 60
              policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60

        resources:
          requests:
            cpu: 1000m
            memory: 128Mi
          limits:
            cpu: 1500m
            memory: 512Mi

        env:
          DB_HOST: "aws-eks-terraform-lab-postgres-primary.c3888iw0yn00.ap-northeast-1.rds.amazonaws.com"
          DB_PRIMARY_HOST: "aws-eks-terraform-lab-postgres-primary.c3888iw0yn00.ap-northeast-1.rds.amazonaws.com"
          DB_READ_HOST: "aws-eks-terraform-lab-postgres-replica.c3888iw0yn00.ap-northeast-1.rds.amazonaws.com"
          DB_PORT: "5432"
          DB_NAME: taskdb
          DB_USER: taskuser

          CACHE_ENABLED: "true"
          CACHE_TTL_SECONDS: "60"
          REDIS_HOST: "redis-master.redis.svc.cluster.local"
          REDIS_PORT: "6379"

          ENABLE_DEBUG_ENDPOINTS: "true"
          DEBUG_SLOW_SECONDS: "0.3"

        ingress:
          enabled: false

        secret:
          create: false
          existingSecret: task-api-runtime-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-task-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
